= How to write a RESTful Web service
:toc: macro
:toclevels: 4
:sectnums:

toc::[]

== Introduction

This README contains a step-by-step guide will help you write the code for a
standardfootnote:[This means it will satisfy the minium requirements layed down
by RFCs https://tools.ietf.org/html/rfc7231[7231],
https://tools.ietf.org/html/rfc7232[7232],
https://tools.ietf.org/html/rfc7233[7233],
https://tools.ietf.org/html/rfc7234[7234] and
https://tools.ietf.org/html/rfc7235[7235].]
https://en.wikipedia.org/wiki/Representational_state_transfer[REST]ful Web
service.

Where applicable, some illustrative code samples will be shown. These code
samples are written in the https://clojure.org/[Clojure] programming language,
using Ring, but the steps here are applicable to many other programming
languages.

Provided in this repository are a number of utility functions, also written in
Clojure, which help us to keep the sample code short. Clojure developers can
make direct use of these utility functions. If you're using a different
language, do feel free to port these utility functions to your own language and
release your own library! But let us know, and we'll maintain a list of such
libraries here.

////
Mention how you should strive not to follow this procedure for every endpoint,
but establish resource metadata which can influence processing and make your
handlers far more reusable and generic.
////

=== Clojure setup

With Clojure's Ring library, we can handle a web request with a function. <<ring-handler>> illustrates a simple function that takes the web request and returns a web response.

[[ring-handler]]
.A simple Ring handler
====
[source,clojure]
----
(fn [req] <1>
  {:status 200 :body "OK"} <2>
)
----
<1> `req` is a Clojure map, containing details of the incoming web request
<2> This map is the value returned from the function. It contains details of the outgoing web response.
====

NOTE: Whether you want to use the 'classic' synchronous single-arity functions, or
asynchronous 3-arity functions, is up to you. This guide supports both.

== Step-by-step Guide

=== Is the service available?

First, check that your service is not overwhelmed with requests.

How you can tell this is beyond the scope of this guide. It might be a feature
of the web listener you are working with. Or you might want to build something
that signals that new web requests should temporarily suspended. If you don't
know, just skip this step, it's optional.

If the service is unavailable, return a 503 (Service Unavailable) response and
exit immediately. We don't want to give the server any _more_ work to do!

====
In Clojure, we can return a map from our handler.

[source,clojure]
----
{:status 503}
----

TIP: For the purposes of brevity, we won't add a message body, like "Service
Unavailable". However, this might be something you choose to do, or add
some Ring 'middleware' that will do this for you.
====

=== Check method is known

The next step is to check whether the request method is one your system recognises.

If not, return a 501.

====
Spin has a utility function called `unknown-method?` which can generate the necessary 501 response:

[source,clojure]
----
(defn unknown-method?
  "When the request method is unknown, return a 501 response."
  [request]
  (when-not
      (contains?
       #{:get :put :post :delete :options :trace :connect}
       (:request-method request))
      {:status 501}))
----

In our handler, we can call it like this:

[source,clojure]
----
(when-let [response (spin/unknown-method? request)]
  response)
----
====

=== Authenticate the request

We now authenticate the request. This can be done by inspecting the request
headers, in particular, the `Authorization` header and establishing any claims
made are true (i.e. they can be trusted). This might involve verifying digital
signatures or performing a query on a database containing sessions.

Such claims and session information can be attached to the request. How you
should do this is up to you and your programming language.

=== Locate the resource

[quote,Section 2 RFC 7231]
____
The target of an HTTP request is called a "resource".
____

The request contains the Uniform Resource Locator (URL), which as its name
suggests, is used to locate the target resource.

But first, what _is_ a resource? A resource can be anything! But for our
purposes, we define a *resource* to be a _value_ (e.g. object, structure,
entity, class instance in our programming language) that provides the following:

* A set of *request method* tokens that indicate the request methods allowed on
  the resource.

* The *representation* (or multiple *representations*) that can be provided (or
  generated) that reflects (or reflect) the current state of the resource.

* Other attributes of the resource that may be useful.

////
The set of *request method* tokens might very well depend on details in the
request. For example, a resource might allow a POST but only if the request is
_authorized_ to do so. So you can make use of any information in the request,
not just the URL, to determine the set of *request method* tokens
allowed. Moreover, if some attribute or attributes of a resource are referred to
in making such a decision, or affect the processing of request methods (at the
minimum, the *request method* in the current request), then these should be
included in the *resource* too.
////

Each representation should consist of a set of *representation metadata* and
enough details to produce a *stream of representation data*.

We now use the *request* to locate and construct this *resource* value.

Of course, we should make use of the request' URL , but we can also use other
information contained in the request headers.

TIP: Try to avoid using the *request method* when locating a resource--a *resource* value should
encompass _all_ its methods.

====
In Clojure, you might choose to use a map as a *resource*.

You can use a router to locate the *resource*. In this example, we're using the
https://github.com/metosin/reitit[Reitit] library.

[source,clojure]
----
(ns my-example
  (:require
    [reitit.core :as r]
    [juxt.spin.alpha :as spin]))

(def router
  (r/router
    [["/api/ping" ::ping
     ["/api/orders/:id" ::order]])))

(defn locate-resource [request]
  (let [target (r/match-by-path router (:url request))]
    (case target
      ::ping {::spin/methods #{:get}
              ::spin/representations []}
      ::order {::spin/methods #{:get :post :put :delete}
               ;; merge order id in here
               ::spin/representations []})))
----

Alternatively, we can resolve the resource in any other way that's
appropriate. For example, since resources can be modelled as data values, they
can be stored in a key/value database. Locating a resource is simply a matter of
looking it up using the URL as the key.

====


=== Validate the request with respect to the resource

Return 400 if the request is not valid

NOTE: TBD - this includes authentication

==== Validate parameters (OpenAPI)

=== Check method allowed

Return a 405 if the method is not allowed on the resource, with an Allow header

==== Authorization

Return 401 if not authenticated, 403 if forbidden

=== Dispatch on the method

Go to the relevant sub-section below, corresponding to the request method.

=== GET/HEAD

==== Select the representation

For example, use pick.

Return 404 if no representations. Return 406 if no acceptable representations.

Return the representation, with validator header fields, payload semantics and
control data (see 7.1, control data).

=== POST

=== PUT

=== DELETE

=== OPTIONS

=== Response

==== Add the Date header

==== Add the Server header



== Spin project details

Spin is an _unbundled_ web library, not a web _framework_.

What's the difference? By our definition, a library is a _set of supporting
utility functions_. In contrast, a framework is a system that calls into your
code, via functions (or callbacks). With a library, the _control_ of the program
is very much with the developer. With a framework, the overall control of the
program is taken away from the developer. This might or might not be a
worthwhile trade, depending on your needs.

=== Status

Spin is still under active development and is ALPHA status, meaning that the API
should be considered unstable and likely to change.

=== Naming

The name 'spin' is a deliberate pun on the word 'web'.

[appendix]
== License

The MIT License (MIT)

Copyright © 2020 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
