= Spin

Spin is an _unbundled_ web library, not a web _framework_.

What's the difference? By our definition, a library is a _set of supporting
utility functions_. In contrast, a framework is a system that calls into your
code, via functions (or callbacks). With a library, the _control_ of the program
is very much with the developer. With a framework, the overall control of the
program is taken away from the developer. This might or might not be a
worthwhile trade, depending on your needs.

== Status

Spin is still in development and is ALPHA status, meaning that the API
should be considered unstable and likely to change.

IMPORTANT: Currently, work on Spin has stopped temporarily and active development of the various utility functions is taking place in https://github.com/juxt/site.


== Naming

The name 'spin' is a deliberate pun on the word 'web'.

== License

----
The MIT License (MIT)

Copyright © 2021 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
----
