= How to write a RESTful Web service
:toc: left
:toclevels: 4
:sectnums:

== Introduction

This README contains a step-by-step guide will help you write the code for a
standard. This means it will satisfy the minium requirements layed down
by RFCs https://tools.ietf.org/html/rfc7231[7231],
https://tools.ietf.org/html/rfc7232[7232],
https://tools.ietf.org/html/rfc7233[7233],
https://tools.ietf.org/html/rfc7234[7234] and
https://tools.ietf.org/html/rfc7235[7235].]
https://en.wikipedia.org/wiki/Representational_state_transfer[REST]ful Web
service.

////
Mention how you should strive not to follow this procedure for every endpoint,
but establish resource metadata which can influence processing and make your
handlers far more reusable and generic.
////

//// insert: intro-language-setup

== Step-by-step Guide

[[check-service-available]]
=== Is the service available?

. Check that your service is not overwhelmed with requests.

. If it is, construct a `503 (Service Unavailable)` response and go to
<<error-response>>. Otherwise, go to <<check-known-method>>.

NOTE: How you can tell this is beyond the scope of this guide. It might be a feature
of the web listener you are working with. Or you might want to build something
that signals that new web requests should temporarily suspended. If you don't
know, just skip this step, it's optional.

//// insert: check-service-available

[[check-known-method]]
=== Check method is known

The next step is to check whether the request method is one your system
recognises.

. Check if the *request method* is recognised, for _any_ resource. If not,
construct a 501 `(Not Implemented)` response and go to <<error-response>>.

//// insert: check-known-method

=== Locate the resource

[quote,Section 2 RFC 7231]
____
The target of an HTTP request is called a "resource".
____

The request contains the Uniform Resource Locator (URL), which as its name
suggests, is used to locate the target resource.

But first, what _is_ a resource? A resource can be anything! But for our
purposes, we define a *resource* to be a _value_ (e.g. object, structure,
entity, class instance in our programming language).

This value should include a set of *request method* tokens that indicate the
request methods allowed on the resource.

It can also include any other attributes of the resource that may be useful
later on (for example, for authorization or method execution).

////
The set of *request method* tokens might very well depend on details in the
request. For example, a resource might allow a POST but only if the request is
_authorized_ to do so. So you can make use of any information in the request,
not just the URL, to determine the set of *request method* tokens
allowed. Moreover, if some attribute or attributes of a resource are referred to
in making such a decision, or affect the processing of request methods (at the
minimum, the *request method* in the current request), then these should be
included in the *resource* too.
////

. Construct the *resource* structure that corresponds to the *URL path* in the
*request*, using any other information in the request as necessary. If no
*resource* corresponds with the path, construct a NULL resource.
+
TIP: Try to avoid using the *request method* when locating a resource--a
*resource* value should encompass _all_ its methods.

//// insert: locate-resource

=== Authorize the request

Now's the time to authorize the request, to ensure the request has the authority
to interact, with the method in the request, on the resource you have located.

Often, this will involve inspecting some data about the resource.

If no authorization is necessary, skip this step.

==== Authenticate the request

If you decide that the request needs to be authorized, the request must contain
the necessary credentials.

These might be provided in the form of an `Authorization` header, by a cookie or
by some other means.

If there are credentials provided in the request, then you should respond with a
401 error response.

Depending on the means of authentication, you might also want to add a
`WWW-Authenticate` header or some else to indicate to the user agent that it
should resend the request with credentials.

Skip to <<error-response>> for how to send an error response.

This can be done by inspecting the request
headers, in particular, the `Authorization` header and establishing any claims
made are true (i.e. they can be trusted). This might involve verifying digital
signatures or performing a query on a database containing sessions.

Such claims and session information can be attached to the request. How you
should do this is up to you and your programming language.

=== Validate the request with respect to the resource

Return 400 if the request is not valid

NOTE: TBD - this includes authentication

==== Validate parameters (OpenAPI)

=== Check method allowed

Return a 405 if the method is not allowed on the resource, with an Allow header

=== Process the *request method*

Go to the relevant procedure below, corresponding to the request method.

. <<get>>
. <<post>>
. <<put>>
. <<delete>>
. <<patch>>
. <<options>>

[[get]]
=== GET (or HEAD)

NOTE: The procedure for HEAD is identical to that of GET, with the exception
that we do not produce any body in the response.

==== Select the representation

Each representation should consist of a set of *representation metadata* and
enough details to produce a *stream of representation data*.

For example, use pick.

Return 404 if no representations. Return 406 if no acceptable representations.

Return the representation, with validator header fields, payload semantics and
control data (see 7.1, control data).

[[post]]
=== POST

[[put]]
=== PUT

[[delete]]
=== DELETE

[[patch]]
=== PATCH

[[options]]
=== OPTIONS

=== Response

==== Add the Date header

==== Add the Server header





[[error-response]]
=== Send an error response

If you want to send an error response, you should decide whether to send a body
in the response. This might contain information about the error and explain to
the user-agent (or human) how to avoid the error in future.

. Perform content negotiation to establish the best representation to send.

. Add the *representation metadata* to the response headers, and stream the
*representation data* as the the *body* of the response.






== Spin project details

Spin is an _unbundled_ web library, not a web _framework_.

What's the difference? By our definition, a library is a _set of supporting
utility functions_. In contrast, a framework is a system that calls into your
code, via functions (or callbacks). With a library, the _control_ of the program
is very much with the developer. With a framework, the overall control of the
program is taken away from the developer. This might or might not be a
worthwhile trade, depending on your needs.

=== Status

Spin is still under active development and is ALPHA status, meaning that the API
should be considered unstable and likely to change.

=== Naming

The name 'spin' is a deliberate pun on the word 'web'.

[appendix]
== Copyright

This documentation is Copyright © 2020 JUXT LTD. All Rights Reserved.

[appendix]
== License

This license is for the Skip library.

----
The MIT License (MIT)

Copyright © 2020 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
----
