= Spin
:toc: macro
:toclevels: 4

_Far more web_ for _much less code_.

Spin is a small Clojure library that helps you write HTTP endpoints that
conform to HTTP.

toc::[]

=== Status

Spin is still under active development and is ALPHA status, meaning that the API
should be considered unstable and likely to change.

=== Naming

The name 'spin' is a deliberate pun on the word 'web'.

== How to write Ring handlers

NOTE: Mention how you should strive not to follow this procedure for every endpoint, but establish resource metadata which can influence processing and make your handlers far more reusable and generic.

=== Check method is known

If not, return a 501

=== Locate the resource

Hold on to the methods of the resource.

=== Validate the request with respect to the resource

Return 400 if the request is not valid

NOTE: TBD - this includes authentication
==== Authentication

==== Validate parameters (OpenAPI)

=== Check method allowed

Return a 405 if the method is not allowed on the resource, with an Allow header

==== Authorization

Return 401 if not authenticated, 403 if forbidden

=== Dispatch on the method

Go to the relevant sub-section below, corresponding to the request method.

=== GET/HEAD

==== Select the representation

For example, use pick.

Return 404 if no representations. Return 406 if no acceptable representations.

Return the representation, with validator header fields, payload semantics and
control data (see 7.1, control data).

=== POST

=== PUT

=== DELETE

=== OPTIONS

=== Response

==== Add the Date header

==== Add the Server header


[appendix]
== License

The MIT License (MIT)

Copyright © 2020 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
