= How to write a RESTful Web service
:toc: left
:toclevels: 4
:sectnums:

== Introduction

This README contains a step-by-step guide will help you write the code for a
standard. This means it will satisfy the minium requirements layed down
by RFCs https://tools.ietf.org/html/rfc7231[7231],
https://tools.ietf.org/html/rfc7232[7232],
https://tools.ietf.org/html/rfc7233[7233],
https://tools.ietf.org/html/rfc7234[7234] and
https://tools.ietf.org/html/rfc7235[7235].]
https://en.wikipedia.org/wiki/Representational_state_transfer[REST]ful Web
service.

Where applicable, some illustrative code samples will be shown. These code
samples are written in the https://clojure.org/[Clojure] programming language,
using Ring, but the steps here are applicable to many other programming
languages.

Provided in this repository are a number of utility functions, also written in
Clojure, which help us to keep the sample code short. Clojure developers can
make direct use of these utility functions. If you're using a different
language, do feel free to port these utility functions to your own language and
release your own library! But let us know, and we'll maintain a list of such
libraries here.

////
Mention how you should strive not to follow this procedure for every endpoint,
but establish resource metadata which can influence processing and make your
handlers far more reusable and generic.
////

//// insert: intro-language-setup

== Step-by-step Guide

=== Is the service available?

First, check that your service is not overwhelmed with requests.

How you can tell this is beyond the scope of this guide. It might be a feature
of the web listener you are working with. Or you might want to build something
that signals that new web requests should temporarily suspended. If you don't
know, just skip this step, it's optional.

If the service is unavailable, return a 503 (Service Unavailable) response and
exit immediately. We don't want to give the server any _more_ work to do!

//// insert: service-available

=== Check method is known

The next step is to check whether the request method is one your system
recognises.

If not, return a 501.

//// insert: unknown-method

=== Locate the resource

[quote,Section 2 RFC 7231]
____
The target of an HTTP request is called a "resource".
____

The request contains the Uniform Resource Locator (URL), which as its name
suggests, is used to locate the target resource.

But first, what _is_ a resource? A resource can be anything! But for our
purposes, we define a *resource* to be a _value_ (e.g. object, structure,
entity, class instance in our programming language).

This value should include a set of *request method* tokens that indicate the
request methods allowed on the resource.

It can also include any other attributes of the resource that may be useful
later on (for example, for authorization or method execution).

////
The set of *request method* tokens might very well depend on details in the
request. For example, a resource might allow a POST but only if the request is
_authorized_ to do so. So you can make use of any information in the request,
not just the URL, to determine the set of *request method* tokens
allowed. Moreover, if some attribute or attributes of a resource are referred to
in making such a decision, or affect the processing of request methods (at the
minimum, the *request method* in the current request), then these should be
included in the *resource* too.
////

We now use the *request* to locate and construct this *resource* value.

Of course, we should make use of the request's URL, but we can also use other
information contained in the request headers.

TIP: Try to avoid using the *request method* when locating a resource--a
*resource* value should encompass _all_ its methods.

//// insert: locate-resource

=== Authenticate the request

We now authenticate the request. This can be done by inspecting the request
headers, in particular, the `Authorization` header and establishing any claims
made are true (i.e. they can be trusted). This might involve verifying digital
signatures or performing a query on a database containing sessions.

Such claims and session information can be attached to the request. How you
should do this is up to you and your programming language.

=== Validate the request with respect to the resource

Return 400 if the request is not valid

NOTE: TBD - this includes authentication

==== Validate parameters (OpenAPI)

=== Check method allowed

Return a 405 if the method is not allowed on the resource, with an Allow header

==== Authorization

Return 401 if not authenticated, 403 if forbidden

=== Dispatch on the method

Go to the relevant sub-section below, corresponding to the request method.

=== GET/HEAD

==== Select the representation

Each representation should consist of a set of *representation metadata* and
enough details to produce a *stream of representation data*.

For example, use pick.

Return 404 if no representations. Return 406 if no acceptable representations.

Return the representation, with validator header fields, payload semantics and
control data (see 7.1, control data).

=== POST

=== PUT

=== DELETE

=== OPTIONS

=== Response

==== Add the Date header

==== Add the Server header



== Spin project details

Spin is an _unbundled_ web library, not a web _framework_.

What's the difference? By our definition, a library is a _set of supporting
utility functions_. In contrast, a framework is a system that calls into your
code, via functions (or callbacks). With a library, the _control_ of the program
is very much with the developer. With a framework, the overall control of the
program is taken away from the developer. This might or might not be a
worthwhile trade, depending on your needs.

=== Status

Spin is still under active development and is ALPHA status, meaning that the API
should be considered unstable and likely to change.

=== Naming

The name 'spin' is a deliberate pun on the word 'web'.

[appendix]
== License

The MIT License (MIT)

Copyright © 2020 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
